/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  sym_number = 6,
  sym_string = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_null = 10,
  sym__identifier_base = 11,
  anon_sym_QMARK = 12,
  anon_sym_COLON = 13,
  sym_operator = 14,
  sym_match_all = 15,
  sym_kw_fn = 16,
  sym_kw_let = 17,
  sym_kw_cond = 18,
  sym_kw_import = 19,
  sym_kw_as = 20,
  sym_kw_raise = 21,
  sym_kw_switch = 22,
  sym_source_file = 23,
  sym__expression = 24,
  sym_sexp = 25,
  sym_list = 26,
  sym_boolean = 27,
  sym_identifier = 28,
  sym__predicate_marker = 29,
  sym_qualified_identifier = 30,
  sym_switch_case = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_sexp_repeat1 = 33,
  aux_sym_sexp_repeat2 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym__identifier_base] = "_identifier_base",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [sym_operator] = "operator",
  [sym_match_all] = "match_all",
  [sym_kw_fn] = "kw_fn",
  [sym_kw_let] = "kw_let",
  [sym_kw_cond] = "kw_cond",
  [sym_kw_import] = "kw_import",
  [sym_kw_as] = "kw_as",
  [sym_kw_raise] = "kw_raise",
  [sym_kw_switch] = "kw_switch",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_sexp] = "sexp",
  [sym_list] = "list",
  [sym_boolean] = "boolean",
  [sym_identifier] = "identifier",
  [sym__predicate_marker] = "_predicate_marker",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_switch_case] = "switch_case",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sexp_repeat1] = "sexp_repeat1",
  [aux_sym_sexp_repeat2] = "sexp_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym__identifier_base] = sym__identifier_base,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_operator] = sym_operator,
  [sym_match_all] = sym_match_all,
  [sym_kw_fn] = sym_kw_fn,
  [sym_kw_let] = sym_kw_let,
  [sym_kw_cond] = sym_kw_cond,
  [sym_kw_import] = sym_kw_import,
  [sym_kw_as] = sym_kw_as,
  [sym_kw_raise] = sym_kw_raise,
  [sym_kw_switch] = sym_kw_switch,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_sexp] = sym_sexp,
  [sym_list] = sym_list,
  [sym_boolean] = sym_boolean,
  [sym_identifier] = sym_identifier,
  [sym__predicate_marker] = sym__predicate_marker,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_switch_case] = sym_switch_case,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sexp_repeat1] = aux_sym_sexp_repeat1,
  [aux_sym_sexp_repeat2] = aux_sym_sexp_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier_base] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_match_all] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_let] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_import] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_as] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_raise] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_switch] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_sexp] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__predicate_marker] = {
    .visible = false,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_switch_case] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sexp_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sexp_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function = 1,
  field_module = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_module] = "module",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 2},
    {field_module, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 4,
        '(', 42,
        ')', 43,
        '*', 92,
        ':', 89,
        ';', 41,
        '?', 88,
        '[', 44,
        ']', 45,
        'a', 27,
        'c', 22,
        'f', 6,
        'i', 20,
        'l', 10,
        'n', 34,
        'r', 7,
        's', 35,
        't', 25,
        '+', 90,
        '-', 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(102);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 4,
        '(', 42,
        ')', 43,
        ';', 41,
        '[', 44,
        'c', 74,
        'f', 57,
        'i', 72,
        'l', 64,
        'n', 85,
        'r', 59,
        's', 86,
        't', 77,
        '+', 90,
        '-', 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 4,
        '(', 42,
        '*', 92,
        ';', 41,
        '[', 44,
        'f', 58,
        'n', 85,
        't', 77,
        '+', 90,
        '-', 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(1);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(103);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(101);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 35:
      if (lookahead == 'w') ADVANCE(15);
      END_STATE();
    case 36:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 4,
        '(', 42,
        ')', 43,
        ':', 89,
        ';', 41,
        '?', 88,
        '[', 44,
        ']', 45,
        'f', 58,
        'n', 85,
        't', 77,
        '+', 90,
        '-', 90,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == '!') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'a') ADVANCE(69);
      if (lookahead == 'n') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'a') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'a') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'c') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'd') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'h') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'i') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'i') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'l') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'l') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'm') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'o') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'o') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'p') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'r') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'r') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 's') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 't') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 't') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 't') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'u') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'u') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__identifier_base);
      if (lookahead == 'w') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__identifier_base);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_match_all);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '|') ADVANCE(91);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_kw_fn);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_kw_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_kw_let);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_kw_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_kw_cond);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_kw_cond);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_kw_import);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_kw_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_kw_as);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_kw_raise);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_kw_switch);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_kw_switch);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39},
  [5] = {.lex_state = 39},
  [6] = {.lex_state = 39},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 39},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 39},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 39},
  [28] = {.lex_state = 39},
  [29] = {.lex_state = 39},
  [30] = {.lex_state = 39},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 39},
  [33] = {.lex_state = 39},
  [34] = {.lex_state = 39},
  [35] = {.lex_state = 39},
  [36] = {.lex_state = 39},
  [37] = {.lex_state = 39},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_match_all] = ACTIONS(1),
    [sym_kw_fn] = ACTIONS(1),
    [sym_kw_let] = ACTIONS(1),
    [sym_kw_cond] = ACTIONS(1),
    [sym_kw_import] = ACTIONS(1),
    [sym_kw_as] = ACTIONS(1),
    [sym_kw_raise] = ACTIONS(1),
    [sym_kw_switch] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(59),
    [sym__expression] = STATE(7),
    [sym_sexp] = STATE(7),
    [sym_list] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_string] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(15),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(9),
    [sym_sexp] = STATE(9),
    [sym_list] = STATE(9),
    [sym_boolean] = STATE(9),
    [sym_identifier] = STATE(4),
    [sym_qualified_identifier] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(23),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(25),
    [sym_kw_fn] = ACTIONS(27),
    [sym_kw_let] = ACTIONS(29),
    [sym_kw_cond] = ACTIONS(31),
    [sym_kw_import] = ACTIONS(33),
    [sym_kw_raise] = ACTIONS(35),
    [sym_kw_switch] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(44),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_number] = ACTIONS(47),
    [sym_string] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(50),
    [anon_sym_false] = ACTIONS(50),
    [sym_null] = ACTIONS(53),
    [sym__identifier_base] = ACTIONS(56),
    [sym_operator] = ACTIONS(53),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(10),
    [sym_sexp] = STATE(10),
    [sym_list] = STATE(10),
    [sym_boolean] = STATE(10),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(61),
    [sym_string] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(63),
    [sym__identifier_base] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(65),
    [sym_operator] = ACTIONS(63),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(10),
    [sym_sexp] = STATE(10),
    [sym_list] = STATE(10),
    [sym_boolean] = STATE(10),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(61),
    [sym_string] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(63),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(63),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(8),
    [sym_sexp] = STATE(8),
    [sym_list] = STATE(8),
    [sym_boolean] = STATE(8),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(67),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(71),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(71),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(77),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(77),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(79),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(77),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(77),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(77),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(77),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(77),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(77),
  },
  [STATE(11)] = {
    [sym__expression] = STATE(12),
    [sym_sexp] = STATE(12),
    [sym_list] = STATE(12),
    [sym_boolean] = STATE(12),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(87),
    [sym_string] = ACTIONS(87),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(89),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(89),
  },
  [STATE(12)] = {
    [sym__expression] = STATE(3),
    [sym_sexp] = STATE(3),
    [sym_list] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_identifier] = STATE(22),
    [sym_qualified_identifier] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_number] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_null] = ACTIONS(77),
    [sym__identifier_base] = ACTIONS(17),
    [sym_operator] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 2,
      sym_number,
      sym_string,
    ACTIONS(95), 2,
      sym_null,
      sym_operator,
    STATE(62), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 3,
      sym_null,
      sym_operator,
      sym_match_all,
    STATE(15), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 2,
      sym_number,
      sym_string,
    ACTIONS(103), 2,
      sym_null,
      sym_operator,
    STATE(56), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [109] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 2,
      sym_number,
      sym_string,
    ACTIONS(107), 2,
      sym_null,
      sym_operator,
    STATE(38), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_QMARK,
    STATE(23), 1,
      sym__predicate_marker,
    ACTIONS(111), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
      anon_sym_COLON,
  [171] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(115), 2,
      sym_number,
      sym_string,
    ACTIONS(117), 2,
      sym_null,
      sym_operator,
    STATE(58), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [206] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(119), 2,
      sym_number,
      sym_string,
    ACTIONS(121), 2,
      sym_null,
      sym_operator,
    STATE(13), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [241] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 2,
      sym_number,
      sym_string,
    ACTIONS(125), 2,
      sym_null,
      sym_operator,
    STATE(19), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [276] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym__identifier_base,
    STATE(22), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(127), 2,
      sym_number,
      sym_string,
    ACTIONS(129), 2,
      sym_null,
      sym_operator,
    STATE(55), 5,
      sym__expression,
      sym_sexp,
      sym_list,
      sym_boolean,
      sym_qualified_identifier,
  [311] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_COLON,
    ACTIONS(133), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
      anon_sym_COLON,
  [355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [535] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [555] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [575] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(179), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 5,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__identifier_base,
      sym_operator,
    ACTIONS(183), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      sym_string,
  [635] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    STATE(39), 2,
      sym_switch_case,
      aux_sym_sexp_repeat2,
  [649] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    STATE(40), 2,
      sym_switch_case,
      aux_sym_sexp_repeat2,
  [663] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    STATE(40), 2,
      sym_switch_case,
      aux_sym_sexp_repeat2,
  [677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(196), 1,
      anon_sym_LBRACK,
    ACTIONS(198), 1,
      sym_kw_as,
  [690] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    ACTIONS(202), 1,
      sym_string,
    STATE(44), 1,
      aux_sym_sexp_repeat1,
  [703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    ACTIONS(206), 1,
      sym_string,
    STATE(43), 1,
      aux_sym_sexp_repeat1,
  [716] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    ACTIONS(211), 1,
      sym_string,
    STATE(43), 1,
      aux_sym_sexp_repeat1,
  [729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(62), 1,
      sym_identifier,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_list,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(215), 1,
      sym_kw_as,
  [759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(30), 1,
      sym_identifier,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(57), 1,
      sym_identifier,
  [779] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(18), 1,
      sym_identifier,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(46), 1,
      sym_identifier,
  [799] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym__identifier_base,
    STATE(61), 1,
      sym_identifier,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    ACTIONS(219), 1,
      sym_kw_as,
  [819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RBRACK,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_string,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 38,
  [SMALL_STATE(15)] = 74,
  [SMALL_STATE(16)] = 109,
  [SMALL_STATE(17)] = 144,
  [SMALL_STATE(18)] = 171,
  [SMALL_STATE(19)] = 206,
  [SMALL_STATE(20)] = 241,
  [SMALL_STATE(21)] = 276,
  [SMALL_STATE(22)] = 311,
  [SMALL_STATE(23)] = 334,
  [SMALL_STATE(24)] = 355,
  [SMALL_STATE(25)] = 375,
  [SMALL_STATE(26)] = 395,
  [SMALL_STATE(27)] = 415,
  [SMALL_STATE(28)] = 435,
  [SMALL_STATE(29)] = 455,
  [SMALL_STATE(30)] = 475,
  [SMALL_STATE(31)] = 495,
  [SMALL_STATE(32)] = 515,
  [SMALL_STATE(33)] = 535,
  [SMALL_STATE(34)] = 555,
  [SMALL_STATE(35)] = 575,
  [SMALL_STATE(36)] = 595,
  [SMALL_STATE(37)] = 615,
  [SMALL_STATE(38)] = 635,
  [SMALL_STATE(39)] = 649,
  [SMALL_STATE(40)] = 663,
  [SMALL_STATE(41)] = 677,
  [SMALL_STATE(42)] = 690,
  [SMALL_STATE(43)] = 703,
  [SMALL_STATE(44)] = 716,
  [SMALL_STATE(45)] = 729,
  [SMALL_STATE(46)] = 739,
  [SMALL_STATE(47)] = 749,
  [SMALL_STATE(48)] = 759,
  [SMALL_STATE(49)] = 769,
  [SMALL_STATE(50)] = 779,
  [SMALL_STATE(51)] = 789,
  [SMALL_STATE(52)] = 799,
  [SMALL_STATE(53)] = 809,
  [SMALL_STATE(54)] = 819,
  [SMALL_STATE(55)] = 827,
  [SMALL_STATE(56)] = 834,
  [SMALL_STATE(57)] = 841,
  [SMALL_STATE(58)] = 848,
  [SMALL_STATE(59)] = 855,
  [SMALL_STATE(60)] = 862,
  [SMALL_STATE(61)] = 869,
  [SMALL_STATE(62)] = 876,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 6, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 6, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 9, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 9, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 3, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 3, 0, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 7, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 7, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 5, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexp, 8, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexp, 8, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sexp_repeat2, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sexp_repeat2, 2, 0, 0), SHIFT_REPEAT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sexp_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sexp_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switch_case, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [227] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_liss(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "liss",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
